grails-app/domain/cn/edu/cup/TomcatInstance.groovy
package cn.edu.cup

class TomcatInstance {

    String tomcatPath
    String wanIP
    String lanIP
    Integer port = 8080

    static hasMany = [userApp: UserApp]

    static constraints = {
        tomcatPath(unique: true)
        wanIP()
        lanIP()
        port()
    }

    String toString() {
        return "${tomcatPath}"
    }
}

grails-app/controllers/cn/edu/cup/TomcatInstanceController.groovy
package cn.edu.cup

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class TomcatInstanceController {

    TomcatInstanceService tomcatInstanceService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond tomcatInstanceService.list(params), model:[tomcatInstanceCount: tomcatInstanceService.count()]
    }

    def show(Long id) {
        respond tomcatInstanceService.get(id)
    }

    def create() {
        respond new TomcatInstance(params)
    }

    def save(TomcatInstance tomcatInstance) {
        if (tomcatInstance == null) {
            notFound()
            return
        }

        try {
            tomcatInstanceService.save(tomcatInstance)
        } catch (ValidationException e) {
            respond tomcatInstance.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tomcatInstance.label', default: 'TomcatInstance'), tomcatInstance.id])
                redirect tomcatInstance
            }
            '*' { respond tomcatInstance, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond tomcatInstanceService.get(id)
    }

    def update(TomcatInstance tomcatInstance) {
        if (tomcatInstance == null) {
            notFound()
            return
        }

        try {
            tomcatInstanceService.save(tomcatInstance)
        } catch (ValidationException e) {
            respond tomcatInstance.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'tomcatInstance.label', default: 'TomcatInstance'), tomcatInstance.id])
                redirect tomcatInstance
            }
            '*'{ respond tomcatInstance, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        tomcatInstanceService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'tomcatInstance.label', default: 'TomcatInstance'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tomcatInstance.label', default: 'TomcatInstance'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tomcatInstance/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'tomcatInstance.label', default: 'TomcatInstance')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-tomcatInstance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-tomcatInstance" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.tomcatInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.tomcatInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.tomcatInstance}" method="POST">
                <fieldset class="form">
                    <f:all bean="tomcatInstance"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/tomcatInstance/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'tomcatInstance.label', default: 'TomcatInstance')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-tomcatInstance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-tomcatInstance" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.tomcatInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.tomcatInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.tomcatInstance}" method="PUT">
                <g:hiddenField name="version" value="${this.tomcatInstance?.version}" />
                <fieldset class="form">
                    <f:all bean="tomcatInstance"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/tomcatInstance/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'tomcatInstance.label', default: 'TomcatInstance')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-tomcatInstance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-tomcatInstance" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${tomcatInstanceList}" />

            <div class="paginationGrails">
                <g:paginate total="${tomcatInstanceCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/tomcatInstance/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'tomcatInstance.label', default: 'TomcatInstance')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-tomcatInstance" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-tomcatInstance" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="tomcatInstance" />
            <g:form resource="${this.tomcatInstance}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.tomcatInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>